In [24]:
import numpy as np
import pandas as pd
from pandas.io.sas.sas_constants import column_type_offset
from sklearn.model_selection import train_test_split

from sklearn.impute import KNNImputer, SimpleImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [25]:
df = pd.read_csv('Titanic-Dataset.csv', usecols=['Age','Pclass','Fare','Survived'])

In [26]:
df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [27]:
df.isnull().mean()*100

Survived     0.00000
Pclass       0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [28]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state = 2)

In [30]:
X_train.head(5)

     Pclass   Age     Fare
30        1  40.0  27.7208
10        3   4.0  16.7000
873       3  47.0   9.0000
182       3   9.0  31.3875
876       3  20.0   9.8458

In [41]:
knn = KNNImputer(n_neighbors=1, weights='distance')

X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)

In [42]:
pd.DataFrame(X_test_trf, columns=X_train.columns)

     Pclass   Age     Fare
0       1.0  42.0  26.2875
1       3.0  21.0   8.0500
2       2.0  24.0  65.0000
3       3.0  28.0  56.4958
4       3.0  17.0   7.9250
..      ...   ...      ...
174     3.0  24.0   8.0500
175     3.0  22.0   9.0000
176     3.0  24.0  69.5500
177     3.0  26.0   7.8958
178     3.0  29.0  10.4625

[179 rows x 3 columns]

In [45]:
lr = LogisticRegression()
lr.fit(X_train_trf, y_train)
y_pred = lr.predict(X_test_trf)
accuracy_score(y_test, y_pred)

0.7206703910614525

In [44]:
# Comparison with simple imputer --> mean

si = SimpleImputer()
X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)